---

# recommended setup for hosting with letsencrypt and without a reverse proxy
leihs_virtual_hosts:
  - { hostname: "leihs.test", ip: "10.64.54.22", logfile_infix: "leihs.test", force_redirect_to_https: true }
  - hostname: '{{leihs_external_hostname}}'
    ip: '10.64.54.22'
    force_redirect_to_https: yes
    ssl_certificate_file: '/etc/ssl/certs/apache-selfsigned.crt'
    ssl_certificate_key_file: '/etc/ssl/private/apache-selfsigned.key'
